### ISSUE TITLE
Resharper layer violates AV2201

### ISSUE THREAD

**Issue by denxorz** [bkoelman/CSharpGuidelinesAnalyzer#109]
#### Analyzer

In the Resharper layer the `BUILTIN_TYPE_REFERENCE_STYLE` is set to `UseClrName`, but AV2201 describes that keywords(aliases) should be used. So I expect it be set to `UseKeyword`.

#### Repro steps

1. Download and apply layer.
1. All system types now get a hint to use the CLR name instead of the keyword.

#### Expected behavior
All system types that are written as CLR name should get a hint to use the keyword. All keywords should be left as is.

#### Actual behavior
All system types now get a hint to use the CLR name instead of the keyword. For example `public int Method(){}` will be changed to `public Int32 Method(){}`.

**Comment by bkoelman** [comment]
Nice catch! I've pushed https://github.com/bkoelman/CSharpGuidelinesAnalyzer/commit/01b436af98dfc04168a3966fa5aa086dd0fc6642 to address this.

**Comment by denxorz** [comment]
Thanks! It works fine now.
