### ISSUE TITLE
Support for .editorconfig

### ISSUE THREAD

**Issue by jnyrup** [bkoelman/CSharpGuidelinesAnalyzer#114]
Other analyzers, both roslyn and community, are configurable via .editorconfig.
e.g. 
```
dotnet_diagnostic.CS0169.severity = none
```

It would be nice if the rules for CSharpGuidelinesAnalyzer could also be configured that way.

**Comment by bkoelman** [comment]
Hi @jnyrup, thanks for the suggestion, that would be nice indeed! I'm wondering what is needed to make that possible, if not already working by default. If you can point me to existing projects that work this way or API docs that describe how/where to implement this it would help.

**Comment by jnyrup** [comment]
So far I haven't been able to find any documentation/PRs/changelogs mentioning the feature.
Without having worked with writing analyzers my best guess is that it "just" requires using a newer `Microsoft.CodeAnalysis.Common`.
Looking in the dll's there was a feature `AnalyzerConfig` introduced in 3.1.0 which mentions "editorconfig".

**Comment by bkoelman** [comment]
Analyzers run inside Visual Studio, so they use the version of roslyn assemblies that ship with VS. I just tried and found this works out-of-the-box. Add the following .editorconfig to the root of your project:

```
root = true
[*.cs]
dotnet_diagnostic.AV1532.severity = error
```

And in Program.cs, add the next code:
```csharp
foreach (var item in new[] { "A" })
{
    foreach (var nested in new[] { "B" })
    {
    }
}
```

This reports AV1532 as error instead of warning.

**Comment by bkoelman** [comment]
There's a tool described at https://docs.microsoft.com/en-us/visualstudio/code-quality/use-roslyn-analyzers?view=vs-2019#set-rule-severity-in-an-editorconfig-file to convert existing .RuleSet files to .editorconfig format, in case you need to (haven't tried it).

**Comment by bkoelman** [comment]
Alternatively, you can change the severity from within Visual Studio, which adds a line to .editorconfig:
![image](https://user-images.githubusercontent.com/10324372/80305651-4aff4200-87be-11ea-89e4-c4ab6a189d1d.png)

**Comment by jnyrup** [comment]
Sorry, I just had to restart Visual Studio to make it read the `.editorconfig` values.

**Comment by bkoelman** [comment]
No problem, good to know this is possible now. :)

**Comment by bkoelman** [comment]
@jnyrup In case it helps, I just published a new version to NuGet related to this. The new build enables to put rule-specific settings in .editorconfig, aside from the general severities (which already worked).

See [docs/Configuration.md](https://github.com/bkoelman/CSharpGuidelinesAnalyzer/blob/master/docs/Configuration.md) for details.
