### ISSUE TITLE
AV1008 (Avoid static classes) colliding with FxCop CA1060 (NativeMethods)

### ISSUE THREAD

**Issue by julianbartel** [bkoelman/CSharpGuidelinesAnalyzer#116]
I would like to discuss, what you think about adding another exception to the `AvoidStaticClassAnalyzer` for classes named _NativeMethods_.
Having `static class NativeMethods` is the usual way for using P/Invoke and encouraged by FxCop CA1060, but this collides with this analyzer.
This could be solved by suppressing AV1008 on that class, but since this is clearly specified and recurring situation, I feel this is better handled in the analyzer itself.
#### Analyzer

AvoidStaticClassAnalyzer 

#### Repro steps

1. Add both FxCop Analyzers and CSharpGuidelinesAnalyzer
2. Create a non-static class which utilizes P/Invoke
3. Resole reported CA1060 by making the class static and name it _NativeMethods_

#### Expected behavior

CA1060 is resolved and no new warnings appear

#### Actual behavior

CA1060 disappears but AV1008 comes up.

**Comment by bkoelman** [comment]
Agreed. An exception should be added for (nested or top-level) classes named `NativeMethods`, `SafeNativeMethods` and `UnsafeNativeMethods`.

**Comment by julianbartel** [comment]
Perfect! 😊 I'm looking forward to send a PR as soon as I have some time.

**Comment by julianbartel** [comment]
I'm sorry I did not find the time to do it, the more I thank you for addressing it now 😊 🎉

**Comment by bkoelman** [comment]
No worries, I had some other work in this repo. And it was minimal effort to take this as part of that.
