### ISSUE TITLE
AV2210: Require warning level 9999

### ISSUE THREAD

**Issue by bart-degreed** [bkoelman/CSharpGuidelinesAnalyzer#121]
The highest warning level used to be 4, until C# 9 added warning level 5. Microsoft now [recommends](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-options/errors-warnings#warninglevel) to use 9999, which should include all future warning levels.

AV2210 should be updated to require level 9999.

**Comment by bkoelman** [comment]
@PaulARoy I've removed the check on warning level (see https://github.com/bkoelman/CSharpGuidelinesAnalyzer/commit/90174eafccf08514c856a1a0a1fa6adcfc15521a for motivation), so once the next release has shipped you can remove any earlier workarounds.
