### ISSUE TITLE
Add records as an exception to AV1561 (max 3 parameters in signature)

### ISSUE THREAD

**Issue by weelink** [bkoelman/CSharpGuidelinesAnalyzer#142]
#### Analyzer

AvoidSignatureWithManyParametersAnalyzer

#### Repro steps

```csharp
public record UserImportedEvent(Guid Id, string ExternalId, string Name, string EmailAddress);
```

#### Expected behavior

No warning, because this is basically the same as:

```csharp
public record UserImportedEvent
{
    public Guid Id { get; init; }
    public string ExternalId { get; init; }
    public string Name { get; init; }
    public string EmailAddress { get; init; }
}
```

But more concise in declaration and usage.

#### Actual behavior

Constructor for 'UserImportedEvent' contains 4 parameters, which exceeds the maximum of 3 parameters[AV1561](https://github.com/dennisdoomen/CSharpGuidelines/blob/5.6.0/_rules/1561.md)

**Comment by bkoelman** [comment]
Did you know the number of parameters is configurable in your project? See https://github.com/bkoelman/CSharpGuidelinesAnalyzer/blob/master/docs/Configuration.md for how to do this.

There's a separate maximum for constructor parameters, because wrapping them in a composite object won't work when they are injected from the IoC container.

**Comment by weelink** [comment]
I've read that document, but it seems this is for all constructor parameters, not just for records. Or have I misunderstood it?

**Comment by bkoelman** [comment]
Yes, that's correct.

As an alternative to configuring a higher threshold: In your example, Name and EmailAddress could be wrapped in a new type Contact to fix the warning.

@dennisdoomen Do you think the rule text should be adapted to treat record structs/classes differently?
