### ISSUE TITLE
Add "Username" as a common exception of AV1710

### ISSUE THREAD

**Issue by dennisdoomen** [bkoelman/CSharpGuidelinesAnalyzer#144]
#### Analyzer

The analyzer for [AV1710](https://csharpcodingguidelines.com//naming-guidelines/#AV1710)

#### Repro steps

1. Create a class or record named `User`
1. Add a property named `Username` to it

#### Expected behavior

Since `Username` is a very common name to identify a user and preferred over `Id`, I think it would be good to add that as an exception. 

#### Actual behavior

`AV1710: Property 'Username' contains the name of its containing type 'User'`

**Comment by bkoelman** [comment]
Yes, I agree. Thanks for bringing it up.
