### ISSUE TITLE
Suggestion: have the Roslyn errors refer to the website and not the GitHub repo.

### ISSUE THREAD

**Issue by dennisdoomen** [bkoelman/CSharpGuidelinesAnalyzer#146]
When the analyzer runs, it creates clickable links to the description of a rule. But it refers to the Markdown content on GitHub and not to the real website. Is that intentional?

**Comment by bkoelman** [comment]
Yes, because it links to the commit SHA that matches the version of the analyzer being used. Not everyone may be using the latest version.

**Comment by dennisdoomen** [comment]
Ah, I understand.
