### ISSUE TITLE
AV1553: Report only for *publicly visible* methods

### ISSUE THREAD

**Issue by bart-vmware** [bkoelman/CSharpGuidelinesAnalyzer#154]

**Comment by bkoelman** [comment]
Closing, I assumed this rule was similar to https://rules.sonarsource.com/csharp/RSPEC-2360/ (Optional parameters should not be used in externally visible methods), but https://github.com/dennisdoomen/CSharpGuidelines/blob/master/_rules/1551.md is actually quite different.
