### ISSUE TITLE
Implement AV1532: Avoid nested loops

### ISSUE THREAD

**Issue by bkoelman** [bkoelman/CSharpGuidelinesAnalyzer#16]
This analyzer should report on for/foreach/while/do loops that are nested within another loop.

**Comment by dennisdoomen** [comment]
Is there a way to configure the maximum depth?

**Comment by bkoelman** [comment]
No, there is not. I usually use `SelectMany` in case the code is simple, so it becomes a one-liner. Otherwise, extract the inner loop into a method or local function.

**Comment by dennisdoomen** [comment]
Clear
