### ISSUE TITLE
Problems with latest version of csc

### ISSUE THREAD

**Issue by Bowman74** [bkoelman/CSharpGuidelinesAnalyzer#98]
#### Analyzer

All

#### Repro steps

- Have a Xamarin iOS or Android project that references Roslyn analyzers through Nuget. 
- Build Project in Visual Studio for Mac with MSBuild selected or using MSBuild on the Mac directly in Terminal.

#### Expected behavior
Roslyn analyzers are run and evaluate code correctly.

#### Actual behavior
# Steps to reproduce
- Have a Xamarin iOS or Android project that references Roslyn analyzers through Nuget. 
- Build Project in Visual Studio for Mac with MSBuild selected or using MSBuild on the Mac directly in Terminal.

# Expected behavior
Roslyn analyzers are run and evaluate code correctly. 

# Actual behavior
Errors similar to the following for are generated for each analyzer and the analyzers are not run
CSC : error CS8032: An instance of analyzer CSharpGuidelinesAnalyzer.Rules.Naming.AvoidMisleadingNamesAnalyzer cannot be created from /Users/kevinford/Documents/Projects/VSLiveCICDDemo/Code/BuildTest/packages/CSharpGuidelinesAnalyzer.1.0.1/analyzers/dotnet/cs/CSharpGuidelinesAnalyzer.dll : Exception has been thrown by the target of an invocation.. [/Users/kevinford/Documents/Projects/VSLiveCICDDemo/Code/BuildTest/iOS/BuildTest.iOS.csproj]

Because of this no project with references to Roslyn analyzer DLLs compile in the newest Visual Studio for Mac.

See the following bug for more information.

https://bugzilla.xamarin.com/show_bug.cgi

**Comment by bkoelman** [comment]
Thanks for reporting this.

The C# compiler that ships with VS2017 Update 3 (and the Mac version I
guess) introduces breaking changes on APIs these analyzers depend on. I've
been working with the Roslyn previews in the last months to address these.
It's just that I didn't have an opportunity yet to release a new version
that is based on the stable compiler bits released earlier this week.

Although I don't have a Mac, I suspect the next release will address these
problems. I'm planning to look into this and release a new version tomorrow.

**Comment by bkoelman** [comment]
Oh, the bug link you posted does not work.

**Comment by bkoelman** [comment]
@Bowman74 I have pushed a new release on NuGet. Can you check if that works for you?

**Comment by Bowman74** [comment]
@bkoelman I have verified that version 2.0.0 corrected the issue in both Xamarin Android and Xamarin.iOS. Since it was a problem in CSC, it probably fixed it for other .Net project types too.

**Comment by bkoelman** [comment]
Thanks for testing.

In case someone gets here at a later time:
Use v1.0.1 for Visual Studio 2015 with Update 2 - Visual Studio 2017 with Update 2. Use v2.0.0 for Visual Studio 2017 with Update 3.
